services:
  db:
    image: postgres:15
    container_name: russia_championship_db
    ports:
      - 5430:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - ./russia_championship_backend/.env-non-dev

  cache:
    image: redis
    container_name: russia_championship_cache
    ports:
      - 6370:6379

  backend:
    build:
      context: ./russia_championship_backend/
    container_name: russia_championship_app
    env_file:
      - ./russia_championship_backend/.env-non-dev
    depends_on:
      - db
      - cache
    command: ["/backend/docker/app.sh"]
    ports:
      - 8001:8000

  celery:
    build:
      context: ./russia_championship_backend/
    container_name: russia_championship_celery
    command: ["/backend/docker/celery.sh"]
    env_file:
      - ./russia_championship_backend/.env-non-dev
    depends_on:
      - cache

  bot:
    build:
      context: ./russia_championship_bot/
    container_name: russia_championship_bot
    command: ["/bot/docker/bot.sh"]
    env_file:
      - ./russia_championship_bot/.env-non-dev
    depends_on:
      - db

volumes:
  postgresdata: