services:
  db:
    image: postgres:15
    container_name: russia_championship_db
    ports:
      - 5430:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - ./russia_championship_backend/.env-non-dev
    networks:
      - app_network

  cache:
    image: redis
    container_name: russia_championship_cache
    ports:
      - 6370:6379
    networks:
      - app_network

  backend:
    build:
      context: ./russia_championship_backend/
    container_name: russia_championship_app
    env_file:
      - ./russia_championship_backend/.env-non-dev
    depends_on:
      - db
      - cache
    command: ["/backend/docker/app.sh"]
    ports:
      - 8000:8000
    networks:
      - app_network

  celery:
    build:
      context: ./russia_championship_backend/
    container_name: russia_championship_celery
    command: ["/backend/docker/celery.sh"]
    env_file:
      - ./russia_championship_backend/.env-non-dev
    depends_on:
      - rabbitmq
    networks:
      - app_network
  
  celery-beat:
    build:
      context: ./russia_championship_backend/
    container_name: russia_championship_celery-beat
    command: ["/booking_app/docker/celery-beat.sh"]
    env_file:
      - ./russia_championship_backend/.env-non-dev
    depends_on:
      - rabbitmq
    networks:
      - app_network

  bot:
    build:
      context: ./russia_championship_bot/
    container_name: russia_championship_bot
    command: ["/bot/docker/bot.sh"]
    env_file:
      - ./russia_championship_bot/.env-non-dev
    depends_on:
      - db
    networks:
      - app_network

  front:
    build:
      context: ./russia_championship_front/
    container_name: russia_championship_front
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: russia_championship_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_network


volumes:
  postgresdata:

networks:
  app_network:
    driver: bridge