"""add yandex and google in model user

Revision ID: af8a07190c36
Revises: 527351c2c637
Create Date: 2024-11-06 10:53:10.322879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8a07190c36'
down_revision: Union[str, None] = '527351c2c637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('yandex_access_token', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'yandex_access_token')
    op.drop_column('user', 'google_access_token')
    # ### end Alembic commands ###
