name: CI/CD for Russia-championship App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout кода
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Настройка SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    # 3. Установим docker-Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    # 5. Создаём файл .env-non-dev для бекенда из секретов
    - name: Create .env-non-dev file for backend
      run: echo "${{ secrets.ENV_NON_DEV_BACK }}" > ./russia_championship_backend/.env-non-dev

    # 6. Создаём файл .env-non-dev для бота из секретов
    - name: Create .env-non-dev file for backend
      run: echo "${{ secrets.ENV_NON_DEV_BOT }}" > ./russia_championship_bot/.env-non-dev

    # 6. Создаём файл .env из секретов
    - name: Create .env file for frontend
      run: echo "${{ secrets.ENV_FRONT }}" > ./russia_championship_front/.env

    # 7. Проверка Docker Compose
    - name: Lint Docker Compose
      run: docker-compose -f docker-compose.yml config

    # 8. Сборка Docker образов
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.yml build

    # 9. Копирование файлов на сервер
    - name: Deploy files to server
      run: |
        ssh -o StrictHostKeyChecking=no los@176.123.167.12 "mkdir -p ~/russia_championship"
        rsync -avz --exclude=".git" ./ los@176.123.167.12:~/russia_championship/

    # 10. Запуск Docker Compose на сервере
    - name: Restart application
      run: |
        ssh -o StrictHostKeyChecking=no los@176.123.167.12 << 'EOF'
          cd ~/russia_championship
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d
        EOF
